language: node_js
notifications:
  webhooks: https://redxtech.me/travis-ci.php
node_js:
  - "node"
  - "lts/*"
before_script:
  - yarn
script:
  - yarn test:ci
  - yarn build
cache:
  yarn: true
  directories:
    - node_modules
